/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTournamentsRouteImport } from './routes/_authenticated/tournaments'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedJoinRouteImport } from './routes/_authenticated/join'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedQuizzesIndexRouteImport } from './routes/_authenticated/quizzes.index'
import { Route as AuthenticatedRoomCodeRouteImport } from './routes/_authenticated/room.$code'
import { Route as AuthenticatedQuizzesQuizIdRouteImport } from './routes/_authenticated/quizzes.$quizId'

const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTournamentsRoute =
  AuthenticatedTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJoinRoute = AuthenticatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizzesIndexRoute =
  AuthenticatedQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoomCodeRoute = AuthenticatedRoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizzesQuizIdRoute =
  AuthenticatedQuizzesQuizIdRouteImport.update({
    id: '/quizzes/$quizId',
    path: '/quizzes/$quizId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guest': typeof GuestRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/join': typeof AuthenticatedJoinRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/play': typeof AuthenticatedPlayRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/tournaments': typeof AuthenticatedTournamentsRoute
  '/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/room/$code': typeof AuthenticatedRoomCodeRoute
  '/quizzes/': typeof AuthenticatedQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guest': typeof GuestRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/join': typeof AuthenticatedJoinRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/play': typeof AuthenticatedPlayRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/tournaments': typeof AuthenticatedTournamentsRoute
  '/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/room/$code': typeof AuthenticatedRoomCodeRoute
  '/quizzes': typeof AuthenticatedQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/guest': typeof GuestRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/join': typeof AuthenticatedJoinRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/tournaments': typeof AuthenticatedTournamentsRoute
  '/_authenticated/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/_authenticated/room/$code': typeof AuthenticatedRoomCodeRoute
  '/_authenticated/quizzes/': typeof AuthenticatedQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/guest'
    | '/challenges'
    | '/dashboard'
    | '/friends'
    | '/join'
    | '/leaderboard'
    | '/play'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/tournaments'
    | '/quizzes/$quizId'
    | '/room/$code'
    | '/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/guest'
    | '/challenges'
    | '/dashboard'
    | '/friends'
    | '/join'
    | '/leaderboard'
    | '/play'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/tournaments'
    | '/quizzes/$quizId'
    | '/room/$code'
    | '/quizzes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/guest'
    | '/_authenticated/challenges'
    | '/_authenticated/dashboard'
    | '/_authenticated/friends'
    | '/_authenticated/join'
    | '/_authenticated/leaderboard'
    | '/_authenticated/play'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/shop'
    | '/_authenticated/tournaments'
    | '/_authenticated/quizzes/$quizId'
    | '/_authenticated/room/$code'
    | '/_authenticated/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  GuestRoute: typeof GuestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tournaments': {
      id: '/_authenticated/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof AuthenticatedTournamentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/join': {
      id: '/_authenticated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthenticatedJoinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quizzes/': {
      id: '/_authenticated/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof AuthenticatedQuizzesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/room/$code': {
      id: '/_authenticated/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof AuthenticatedRoomCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quizzes/$quizId': {
      id: '/_authenticated/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizzesQuizIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedJoinRoute: typeof AuthenticatedJoinRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedTournamentsRoute: typeof AuthenticatedTournamentsRoute
  AuthenticatedQuizzesQuizIdRoute: typeof AuthenticatedQuizzesQuizIdRoute
  AuthenticatedRoomCodeRoute: typeof AuthenticatedRoomCodeRoute
  AuthenticatedQuizzesIndexRoute: typeof AuthenticatedQuizzesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChallengesRoute: AuthenticatedChallengesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedJoinRoute: AuthenticatedJoinRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedTournamentsRoute: AuthenticatedTournamentsRoute,
  AuthenticatedQuizzesQuizIdRoute: AuthenticatedQuizzesQuizIdRoute,
  AuthenticatedRoomCodeRoute: AuthenticatedRoomCodeRoute,
  AuthenticatedQuizzesIndexRoute: AuthenticatedQuizzesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  GuestRoute: GuestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
